#!/bin/bash

let array_length=${#@}-1
SORTED=()
FILMS=()
ERRORS=()
red=$(tput setaf 1)
tan=$(tput setaf 3)
green=$(tput setaf 76)
reset=$(tput sgr0)

# Check for no arguments empty array then exit?
if [ ${#BASH_ARGV[@]} = 0 ]; then
  echo "Your missing your first argument"
  exit
fi

# reverse the BASH_ARGV array so it's sorted
# create new sorted array
function reverse_arr() {
  for ((i=$array_length; i>=0; i--)); do
    SORTED+=(${BASH_ARGV[$i]})
  done
  GENRE=${SORTED[0]}
}

# seperate the first argument from the rest create a FILMS array
# calls error_log function
function film_arr() {
  for film in ${SORTED[@]}; do
    if [ $film != $GENRE ]; then
      FILMS+=($film)
    fi
  done
}

#rsyc function
function mvrf() {
  src=$1
  echo $src
  rsync -aP $src /Volumes/Entertainment/movies/$GENRE
  rm -rf $src
  note_film $src
}

# if no source arguments were given exit
# display errors if any
function error_log() {
  if [ ${#FILMS[@]} == 0  ]; then
    ERRORS+=('Missing source. Genre must  be different then source')
  fi
  if [ ${#ERRORS[@]} -eq 0 ]; then
    for film in ${FILMS[@]}; do
      mvrf $film &
    done
  else
    for ((error = 0; error < ${#ERRORS[@]}; error++)); do
      printf "${red} ✖ ${ERRORS[$error]} %s${reset}\n" 
    done
  fi
}

#Display notifications when movies transferred
function note_film(){
  movie_name=$1
  osascript -e 'display notification "Success: Transfer Complete => '$movie_name'" with title "Film  Transfer"'
}


reverse_arr
printf "${tan} ➜ Genre: $GENRE %s${resetl}\n"
film_arr
printf "${tan} ➜ Sources: ${FILMS[@]} %s${reset}\n"
error_log
